import { Country } from './types';

export const COUNTRIES: Country[] = [
  {
    id: 'uzb',
    name: 'Uzbekistan',
    flag: '🇺🇿',
    capital: 'Tashkent',
    population: 36024946,
    area: 447400,
    region: 'Central Asia',
  },
  {
    id: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    capital: 'Washington, D.C.',
    population: 331449281,
    area: 9833517,
    region: 'Americas',
  },
  {
    id: 'ger',
    name: 'Germany',
    flag: '🇩🇪',
    capital: 'Berlin',
    population: 83190556,
    area: 357022,
    region: 'Europe',
  },
  {
    id: 'jpn',
    name: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    population: 125584838,
    area: 377975,
    region: 'Asia',
  },
  {
    id: 'bra',
    name: 'Brazil',
    flag: '🇧🇷',
    capital: 'Brasília',
    population: 214326496,
    area: 8515767,
    region: 'Americas',
  },
  {
    id: 'fra',
    name: 'France',
    flag: '🇫🇷',
    capital: 'Paris',
    population: 67500000,
    area: 551695,
    region: 'Europe',
  },
  {
    id: 'can',
    name: 'Canada',
    flag: '🇨🇦',
    capital: 'Ottawa',
    population: 38246108,
    area: 9984670,
    region: 'Americas',
  },
  {
    id: 'aus',
    name: 'Australia',
    flag: '🇦🇺',
    capital: 'Canberra',
    population: 25890773,
    area: 7692024,
    region: 'Oceania',
  },
];
